version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      # - ./dbscripts/init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh
      # - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/postgresql/data
volumes:
  postgres: